language: ruby
rvm:
- 2.3.1
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
    secure: GIT_NAME="sabgaby" GIT_EMAIL="sab.gaby@gmail.com" GH_TOKEN=c58efa488376a67eb73edba37701e15a19f2c2ab
