# Site settings
title: sabgaby
email: gabriela.sanchez@unige.ch
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: sabgaby
github_username:  sabgaby

# Build settings
markdown: kramdown
permalink: /:title

include: ["_pages", "_works"]
exclude: ["vendor", "Gemfile", "Gemfile.lock", "README.md", "node_modules", "gulpfile.js", "semantic.json"]

collections:
  works:
    output: true

plugins:
  - jemoji
  - algoliasearch-jekyll

defaults:
  -
    scope:
      type: posts
    values:
      layout: post
  -
    scope:
      type: pages
    values:
      layout: page

  -
    scope:
      type: works
    values:
      layout: work
      collection: work

algolia:
  application_id: '0ZOC7G44GQ'
  index_name: 'sabgaby'
  read_only_api_key: 'af5d43c2fe4dd921be946e80957a18db'
  lazy_update: true
  settings:
    advancedSyntax: true
    distinct: true
    attributeForDistinct: 'url'
    ignorePlurals: true
    attributesToIndex:
      - title
      - chapter
      - subtitle
      - description
      - date
      - pretty-date
      - unordered(text)
      - unordered(tags)
      - parent
      - url
      - slug
      - flow
    attributesForFaceting:
      - title
      - chapter
      - date
      - pretty-date
      - tags
      - parent
      - flow
    attributesToRetrieve:
      - title
      - subtitle
      - description
      - chapter
      - date
      - pretty-date
      - pdf
      - slides
      - tags
      - parent
      - url
      - slug
      - flow
    attributesToSnippet: ['text:20']
    snippetEllipsisText: '[&hellip;]'
    attributesToHighlight: ['*']
    highlightPostTag: </span>
    highlightPreTag: <span class="search-highlight">
    minWordSizefor1Typo: 3
    minWordSizefor2Typos: 7
  excluded_files:
    - 404.html





# Embeds

# API keys
